MAIN – Droplets Simulation
MAIN Program
14 statements
Source File
Uses
dropletMotionSimulation
caseName_m
Simulation of Virus-Laden Droplets Behavior in AFDET by KIYOTA OGURA(2021/1/10) updated by YUTA IDA
Calls
Contents
Variables
nc nc_max
Variables
Type Attributes Name Initial
integer, pointer :: nc => nowCase
integer :: nc_max
Call graph
main calls get_casename, case_check, maindropletloop, read_basicsettingonsimulation, simulationsetup, output_resultsummary
case_check calls read_textrecord
simulationsetup calls dropletgenerator_, dropletequationsolver_, read_backup, flowfield_
output_resultsummary calls nowdateandtime
dropletequationsolver_ calls basicparameter_
flowfield_ calls flowfieldunstructuredgrid_
flowfieldunstructuredgrid_ calls get_dirfrompath