cellCenterCalc_test – Droplets Simulation
cellCenterCalc_test Program
14 statements
Source File
Uses
geometry_m
unstructuredGrid_m
Calls
Contents
Variables
grid centers vertices i imax
Variables
Type Attributes Name Initial
type(FlowFieldUnstructuredGrid) :: grid
real, allocatable :: centers(:,:)
real, allocatable :: vertices(:,:)
integer :: i
integer :: imax
Call graph
cellcentercalc_test calls insidejudgment_tetra
insidejudgment_tetra calls volume_tetra
volume_tetra calls cross_product
cross_product calls cross_product_dble, cross_product_real